openapi: "3.0.0"
info:
  title: Temporary Price Emitter API
  version: '0.1'
paths:
  /price/range/{tokenPair}/{interval}/{startTime}/{endTime}:
    get:
      operationId: main.get_price_from_timerange
      responses:
        200:
          description: get a list of prices from timerange
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    price:
                      type: number
                      format: float
                    timestamp:
                      type: integer
      parameters:
        - name: tokenPair
          in: path
          required: true
          schema:
            type: string
        - name: interval
          in: path
          required: true
          schema:
            type: string
        - name: startTime
          in: path
          required: true
          schema:
            type: integer
        - name: endTime
          in: path
          required: true
          schema:
            type: integer
